name: Update Schedule

on:
  schedule:
    - cron: '0 5 * * *' # Запуск в 8:00 по МСК
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновили с v3 на v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновили с v4 на v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pdfplumber requests

      - name: Run parser
        run: python parser.py
